{{- $name := include "apigwmm.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "ocelot-{{ $name }}"
  labels:
    app: {{ template "apigwmm.name" . }}
    chart: {{ template "apigwmm.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  mm: |-
    {{ (.Files.Glob "configuration-mobile-marketing.json").AsConfig }}

