version: '2'

services:
  basket.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  catalog.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  identity.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  ordering.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  marketing.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  webspa:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  webmvc:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  webstatus:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  locations.api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
