version: '2'


services:
  sagamanager:
    image: eshop/sagamanager
    build:
      context: ./src/Services/SagaManager/SagaManager
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  basket.api:
    image: eshop/basket.api
    build:
      context: ./src/Services/Basket/Basket.API
      dockerfile: Dockerfile
    depends_on:
      - basket.data
      - identity.api

  catalog.api:
    image: eshop/catalog.api
    build:
      context: ./src/Services/Catalog/Catalog.API
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  identity.api:
    image: eshop/identity.api
    build:
      context: ./src/Services/Identity/Identity.API
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  ordering.api:
    image: eshop/ordering.api
    build:
      context: ./src/Services/Ordering/Ordering.API
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  webspa:
    image: eshop/webspa
    build:
      context: ./src/Web/WebSPA
      dockerfile: Dockerfile
    depends_on:
      - identity.api
      - basket.api

  webmvc:
    image: eshop/webmvc
    build:
      context: ./src/Web/WebMVC
      dockerfile: Dockerfile
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api

  sql.data:
    image: microsoft/mssql-server-linux

  basket.data:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  webstatus:
    image: eshop/webstatus
    build:
      context: ./src/Web/WebStatus
      dockerfile: Dockerfile

  payment.api:
    image: eshop/payment.api
    build:
      context: ./src/Services/Payment/Payment.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
