version: '2.1'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - .:/src
      - ./cli-linux:/cli-linux
    working_dir: /src

#   Next line is using the .sln file to compile all the projects. 
#   Sometime there is an issue in msbuild exits the process before finishing building the bits: (https://github.com/Microsoft/msbuild/issues/2153)
#   Random error: error MSB4017: The build stopped unexpectedly be cause of an unexpected logger failure.
    #command: /bin/bash -c "pushd ./src/Web/WebSPA && npm rebuild node-sass && popd && dotnet restore ./eShopOnContainers-ServicesAndWebApps.sln  --verbosity minimal && dotnet publish ./eShopOnContainers-ServicesAndWebApps.sln -c Release -o ./obj/Docker/publish --verbosity minimal"

#    NOTE: Using build-bits-linux.sh from Linux build container exits before ending.
    command: /bin/bash -c "pushd ./src/Web/WebSPA && npm rebuild node-sass && popd && pushd /cli-linux && ./build-bits-linux.sh /src"
    