{{- $name := include "basket-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "basket-api.name" . }}
    chart: {{ template "basket-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  basket__ConnectionString: {{ .Values.inf.redis.basket.constr }}
  urls__IdentityUrl: http://{{ .Values.app.svc.identity }}
  basket__EnableLoadTest: "{{ .Values.inf.misc.useLoadTest }}"
  all__EventBusConnection: {{ .Values.inf.eventbus.constr }}
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"