{{- $root := . }}
{{- range $name, $values := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "catalogapi.fullname" $root }}-{{ $name | lower }}
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
