{{- $name := include "webmvc.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $webshoppingapigw := include "url-of" (list .Values.app.ingress.entries.webshoppingapigw .) -}}
{{- $mvc := include "url-of" (list .Values.app.ingress.entries.mvc .) -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webmvc.name" . }}
    chart: {{ template "webmvc.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"
  all_EnableLoadTest: "{{ .Values.inf.misc.useLoadTest }}"
  webmvc__keystore: {{ .Values.inf.redis.keystore.constr }}
  internalurls__apigwws: http://{{ .Values.app.svc.webshoppingapigw }}
  internalurls__apigwwm: http://{{ .Values.app.svc.webmarketingapigw }}
  internalurls__identity__hc: http://{{ .Values.app.svc.identity }}/hc
  urls__apigwws: {{ $protocol }}://{{ $webshoppingapigw }}
  urls__mvc: {{ $protocol }}://{{ $mvc }}
  urls__IdentityUrl: {{ $protocol }}://{{ $identity }}
