{{- $name := include "apigwms.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "envoy-{{ $name }}"
  labels:
    app: {{ template "apigwms.name" . }}
    chart: {{ template "apigwms.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ (.Files.Glob "envoy.yaml").AsConfig | indent 2 }}

