# This heml values file defines all infrastructure used by eShopOnContainers.
# It is used on all charts, so ** MUST BE INCLUDED ** on every deployment

inf:
  sql:                      # inf.sql defines the sql server databases & logins
#    host:  my-sql-server   # Uncomment to specify a custom sql-server to be used. By default "sql-data-<appname>" will be used  
    common:
      user: sa              # SQL user
      pwd: Pass@word        # SQL pwd
      pid: Developer
    catalog:                # inf.sql.catalog: settings for the catalog-api sql (user, pwd, db)
      db: CatalogDb         # Catalog API SQL db name
    ordering:               # inf.sql.ordering: settings for the ordering-api sql (user, pwd, db)
      db: OrderingDb        # Ordering API SQL db name
    identity:
      db: IdentityDb        # Ordering API SQL db name
    marketing:
      db: MarketingDb        # Marketing API SQL db name
    webhooks:
      db: WebhooksDb            # Webhooks DB
  mongo:
#    host: my-nosql-data     # Uncomment to use specify custom mongo host. By default nosql-data is used
    locations:
      database: LocationsDb
    marketing:
      database: MarketingDb
  redis:                    # inf.redis defines the redis' connection strings
    basket:     
      svc: basket-data      # Name of k8s svc for basket redis     
      constr: basket-data   # Connection string to Redis used by Basket API
    keystore:
      svc: keystore-data    # Name of k8s svc for keystore-data redis
      constr: keystore-data # Connection string to Redis used as a Keystore (by Identity API)
  eventbus:
    svc: rabbitmq           # Name of k8s svc for rabbitmq
    constr: rabbitmq        # Event bus connection string
    useAzure: false         # true if use Azure Service Bus. False if RabbitMQ
  appinsights:
      key: ""               # App insights to use
  k8s:                      # inf.k8s defines Kubernetes cluster global config
    dns:  ""                # k8s external  DNS. This value or ip value MUST BE PROVIDED
  misc:                     # inf.misc contains miscellaneous configuration related to infrastructure
    useLoadTest: false      # If running under loading test or not
    useAzureStorage: false  # If catalog api uses azure storage or not
#  registry:                # Uncomment "registry" to specify registry secret
#    secretName:            # secretName is the name of the secret inside k8s   
#    server:                # Registry login server
#    login:                 # User login
#    pwd:                   # User pwd

