version: '2.1'

services:
  catalog.webforms:
    image: catalog.webforms
    build:
      context: .\Catalog.WebForms
      dockerfile: Dockerfile
    depends_on:
      - catalog.api

  catalog.api:
    image: eshop/catalog.api
    build:
      context: ../../Services/Catalog/Catalog.API
      dockerfile: Dockerfile.nanowin
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-windows
   
