kind: ConfigMap
apiVersion: v1
metadata:
  name: ordering-cm
  labels:
    app: eshop
    service: ordering
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  AzureServiceBusEnabled: "False"
  CheckUpdateTime: "30000"
  ConnectionString: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word
  EventBusConnection: rabbitmq
  GRPC_PORT: "81"
  identityUrl: http://identity-api
  IdentityUrlExternal: http://{{ .Values.aksLB }}/identity
  OrchestratorType: K8S
  PATH_BASE: /ordering-api
  PORT: "80"
  Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ: Verbose
  Serilog__MinimumLevel__Override__ordering.api: Verbose
  UseCustomizationData: "True"
