# This file contains specific services build and images for Windows Containers.
#
# MUST be used alongside "docker-compose.yml" in all windows container commands

version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-windows-developer

  nosql.data:
    image: mongo:windowsservercore

  basket.data:
    image: redis:nanoserver

  rabbitmq:
    image: spring2/rabbitmq

  identity.api:
    build:
      args:
        NODE_IMAGE: stefanscherer/node-windows:8.11

  webspa:
    build:
      args:
        NODE_IMAGE: stefanscherer/node-windows:8.11

  webmvc:
    build:
      args:
        NODE_IMAGE: stefanscherer/node-windows:8.11


networks:
  default:
    external:
      name: nat