name: Deploy webmvc

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - deploy
  workflow_run:
    workflows: ["webmvc"]
    branches: [dev]
    types: [completed]

env:
  CHART: webmvc
  NAMESPACE: eshop
  CHART_ROOT: deploy/k8s/helm

jobs:
  deploy-to-k8s:
    #if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/workflows/composite/deploy-helm
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          chart: ${{ env.CHART }}
          chart_root: ${{ env.CHART_ROOT }}
          namespace: ${{ env.NAMESPACE }}
